// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleId } from "./module";

/**
 * 某个 manifest 的持久设置——配一次、反复跑任务都复用，跟单次任务的参数
 * （`domain::task::NewTask::params`）是两回事：那个每次建任务都要重新给。
 */
export type ManifestConfig = { moduleId: ModuleId, manifestKey: string, config: Record<string, unknown>, updatedAt: string, };

export type SetManifestConfig = { moduleId: ModuleId, manifestKey: string, config: Record<string, unknown>, };
