// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Manifest = { key: string, order: number, name: string, category: string, description: string, tags: Array<string>, icon: string, status: ManifestStatus, entry: string, isQueue: boolean, };

export type ManifestStatus = "available" | "disabled" | "unavailable";
