// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Manifest = { key: string, order: number, name: string, category: string, description: string, tags: Array<string>, icon: string, status: ManifestStatus, entry: string, methods: Array<MethodDescriptor>, metadata: Record<string, unknown>, };

export type ManifestStatus = "available" | "disabled" | "unavailable";

export type MethodDescriptor = { name: string, label: string, params: Array<ParamDescriptor>, };

export type ParamDescriptor = { name: string, label: string, kind: ParamKind, required: boolean, default: unknown, options: Array<ParamOption> | null, };

export type ParamKind = "string" | "number" | "bool" | "enum" | "path";

export type ParamOption = { value: string, label: string, };
