// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 插件目录的顶层分类，对应 `plugins/<as_str()>/` 目录名。
 */
export type ModuleId = "tools" | "crawler";
