// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleId } from "./module";

export type CreateTaskResult = { taskUid: string, };

export type NewTask = { moduleId: ModuleId, manifestKey: string, params: Record<string, unknown>, };

export type Task = { id: number, taskUid: string, moduleId: ModuleId, manifestKey: string, title: string, paramsJson: string, resultJson: string | null, status: TaskStatus, progress: number, total: number, done: number, errorMessage: string | null, createdAt: string, updatedAt: string, startedAt: string | null, finishedAt: string | null, };

/**
 * 队列侧的状态操作——都只是改数据库里的记录，不涉及真正终止/唤起一个执行中的进程
 * （执行引擎落地前，任务永远不会真的处于"有进程在跑"的中间态）。
 */
export type TaskActionKind = "cancel" | "pause" | "resume" | "retry" | "restart";

export type TaskStatus = "pending" | "running" | "paused" | "success" | "failed" | "canceled" | "interrupted";
