// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveWeather = { province: string, city: string, adcode: string, weather: string, temperature: string, winddirection: string, windpower: string, humidity: string, reporttime: string, };
